### ISSUE TITLE
DeletionPolicy common property does not seem to work for EIPAssosciation

### ISSUE THREAD

**Issue by MartinSGill** [localytics/humidifier#45]
I've been trying out humidifier by converting one of our existing CFNs to use it, as such I know that the JSON version of the CFN I have works correctly.

I was expecting this code

```ruby
stack.add('AssociateEIP', Humidifier::EC2::EIPAssociation.new(
    deletion_policy: 'Retain',
    allocation_id: Humidifier::Ref.new('EIPAllocationId'),
    instance_id: Humidifier::Ref.new('Server'),
))
```

to generate:

```json
               "AssociateEIP": {
			"Type": "AWS::EC2::EIPAssociation",
			"DeletionPolicy": "Retain",
			"Properties": {
				"AllocationId": { "Ref": "EIPAllocationId" },
				"InstanceId": { "Ref": "Server" }
			}
		}
```

As described by: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html

Instead I get an error::

```
C:/tools/ruby-2.2.4-i386-mingw32/lib/ruby/gems/2.2.0/gems/humidifier-0.1.2/lib/humidifier/resource.rb:94:in `validate_property': Attempting to set invalid property for Humidifier::EC2::EIPAssociation: deletion_policy (ArgumentError)
	from C:/tools/ruby-2.2.4-i386-mingw32/lib/ruby/gems/2.2.0/gems/humidifier-0.1.2/lib/humidifier/resource.rb:50:in `update_property'
	from C:/tools/ruby-2.2.4-i386-mingw32/lib/ruby/gems/2.2.0/gems/humidifier-0.1.2/lib/humidifier/resource.rb:44:in `block in update'
	from C:/tools/ruby-2.2.4-i386-mingw32/lib/ruby/gems/2.2.0/gems/humidifier-0.1.2/lib/humidifier/resource.rb:44:in `each'
	from C:/tools/ruby-2.2.4-i386-mingw32/lib/ruby/gems/2.2.0/gems/humidifier-0.1.2/lib/humidifier/resource.rb:44:in `update'
	from C:/tools/ruby-2.2.4-i386-mingw32/lib/ruby/gems/2.2.0/gems/humidifier-0.1.2/lib/humidifier/resource.rb:14:in `initialize'
```

I also tried to following, but .add only takes 2 parameters.

```ruby
stack.add('AssociateEIP', Humidifier::EC2::EIPAssociation.new(
    allocation_id: Humidifier::Ref.new('EIPAllocationId'),
    instance_id: Humidifier::Ref.new('Server'),
    ), 
   deletion_policy: 'Retain',
)
```

**Comment by kddeisz** [comment]
Hi @MartinSGill,

Yeah we went back and forth on this when we were designing Humidifier. We figured it was actually confusing to put top-level attributes along with properties. Maybe that was wrong, but for now the way you would do this would be:

```
eip_association = Humidifier::EC2::EIPAssociation.new(
  allocation_id: Humidifier::Ref.new('EIPAllocationId'),
  instance_id: Humidifier::Ref.new('Server'),
)
eip_association.deletion_policy = 'Retain'
stack.add('AssociateEIP', eip_association)
```

or

```
stack.add('AssociateEIP', Humidifier::EC2::EIPAssociation.new(
  allocation_id: Humidifier::Ref.new('EIPAllocationId'),
  instance_id: Humidifier::Ref.new('Server'),
))
stack.resources['AssociateEIP'].deletion_policy = 'Retain'
```

I'm partial to the first approach since stack.resources feels like you're reaching into internals.

**Comment by MartinSGill** [comment]
Ok, that helps, and thanks @kddeisz for the quick response.

Given knowledge of the actual JSON structure, would not a third parameter, a hash, on the add method remove the need for that extra assignment? Like my 2nd attempt above, just for the common parameters?

```ruby
stack.add('AssociateEIP', Humidifier::EC2::EIPAssociation.new(
    allocation_id: Humidifier::Ref.new('EIPAllocationId'),
    instance_id: Humidifier::Ref.new('Server'),
    ), 
   deletion_policy: 'Retain',
)
```

**Comment by kddeisz** [comment]
Yeah that seems to make sense. I've opened a PR with that suggestion implemented. I'll get some review on it and if other people like it I'll cut a new gem at the beginning of next week.

**Comment by kddeisz** [comment]
@MartinSGill Version `0.2.0` has this functionality, just pushed it up
